name: Build Kernel

on:
  push:
    branches: [ lineage-23.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: mlm-games/simple-kernel-build-action@v1
      with:
        KERNEL_CLONE_CMD: 'git clone https://github.com/noobcjk/sukisu/ -b lineage-23.2' # PSA: directory and depth=1 are added automatically!
        KERNEL_CONFIG: 'sm8150_defconfig'
        ARCH: 'arm64'
        TOOLCHAIN_CLONE_CMD: 'git clone https://github.com/djb77/aarch64-linux-android-4.9 ./toolchain/gcc'
        ENABLE_CCACHE: 'true'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: 'kernel_source/flashable-anykernel.zip' # Always named flashable-anykernel.zip
