name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Oneplus 7T kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/noobcjk/sukisu/
          kernel-branch: lineage-23.2
          config: /vendor/sm8150_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
